version: '3.3'

services:
  backend:
    container_name: backend
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tesdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8001:8081"
  
  db:
    container_name: db
    image: postges:14.7
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tesdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: